### PR TITLE
 Go fixes

### PR DESCRIPTION
**Pull request by JacobGros**
This PR fixes the gosec and golint errors.
Also adds actions and a PR template. 
Updates go to 1.17

Tests ran:
powerflex unit & integration
built PowerFlex image and ran cert-csi certify suite , vgs helm test

### CODE REVIEW

**Review by jooseppi-luna — APPROVED** [review]
LGTM

**Comment by bharathsreekanth** [comment]
@JacobGros Generic question, should we consider updating go version in go mod to 1.17 as part of the PR?

**Comment by JacobGros** [comment]
> @JacobGros Generic question, should we consider updating go version in go mod to 1.17 as part of the PR?

Updated Go

**Comment by shanmydell** [comment]
@JacobGros : Shall we update the golang to 1.18 as per recent discussions

**Pull request merged**
